# Assignment: Data Wrangling

### Reading material: `tidy_data.pdf`

**Q1.** This question provides some practice cleaning variables which have common problems.
1. For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. For the Minnesota police use of for data, `./data/mn_police_use_of_force.csv`, clean the `subject_injury` variable, handling the NA's; this gives a value `Yes` when a person was injured by police, and `No` when no injury occurred. What proportion of the values are missing? Is this a concern? Cross-tabulate your cleaned `subject_injury` variable with the `force_type` variable. Are there any patterns regarding when the data are missing?

**Q2.** Go to https://sharkattackfile.net/ and download their dataset on shark attacks (Hint: `GSAF5.xls`).

1. Open the shark attack file using Pandas. It is probably not a csv file, so `read_csv` won't work.
2. Drop any columns that do not contain data.
3. Clean the year variable. Describe the range of values you see. Filter the rows to focus on attacks since 1940. Are attacks increasing, decreasing, or remaining constant over time?
4. Clean the Age variable and make a histogram of the ages of the victims.
5. What proportion of victims are male?
6. Clean the `Type` variable so it only takes three values: Provoked and Unprovoked and Unknown. What proportion of attacks are unprovoked?

---

## *Phase 1: Solution without AI

Complete all questions in the following cells without generative AI. Then commit and push the
notebook before beginning Phase 2.

**Declaration:** I completed this version without generative AI.

**Student(s):** [To be provided]

**Date:** [To be provided]

In [ ]:
# Your Phase 1 solution to the problem goes here.

In [31]:
# Question 1.1

from google.colab import files
uploaded = files.upload()

In [35]:
#importing pandas and uploading csv into collab and using df.head which gives first five rows to get a sense of what the data looks like
import pandas as pd
df = pd.read_csv("airbnb_hw.csv")
df.head()

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [36]:
#Using the describe function to understand a little more about the price column and seeing that it is the wrong data type
df["Price"].describe()

count     30478
unique      511
top         150
freq       1481
Name: Price, dtype: object

In [39]:
#Deleting any commas in the price column by replacing the comma with nothing in order to be able to convert it to numeric
df["Price"] = df["Price"].replace(",", "", regex=True)

In [43]:
#converting data type to integers as opposed to string/object
df["Price"] = pd.to_numeric(df["Price"])

In [45]:
#checking that a row that I know has a comma no longer has one
#checking that the max value in the price column is correct and no longer displaying as 999
df.iloc[101]
df["Price"].max()

10000

In [47]:
#checking that there are no errors
df["Price"].isna().sum()

np.int64(0)

In [49]:
#Question 1.2
from google.colab import files
uploaded = files.upload()

Saving mn_police_use_of_force.csv to mn_police_use_of_force.csv

In [51]:
df2 = pd.read_csv("mn_police_use_of_force.csv")
df2.head()

,response_datetime,problem,is_911_call,primary_offense,subject_injury,force_type,force_type_action,race,sex,age,type_resistance,precinct,neighborhood
0,2016/01/01 00:47:36,Assault in Progress,Yes,DASLT1,NaN,Bodily Force,Body Weight to Pin,Black,Male,20.0,Tensed,1,Downtown East
1,2016/01/01 02:19:34,Fight,No,DISCON,NaN,Chemical Irritant,Personal Mace,Black,Female,27.0,Verbal Non-Compliance,1,Downtown West
2,2016/01/01 02:19:34,Fight,No,DISCON,NaN,Chemical Irritant,Personal Mace,White,Female,23.0,Verbal Non-Compliance,1,Downtown West
3,2016/01/01 02:28:48,Fight,No,PRIORI,NaN,Chemical Irritant,Crowd Control Mace,Black,Male,20.0,Commission of Crime,1,Downtown West
4,2016/01/01 02:28:48,Fight,No,PRIORI,NaN,Chemical Irritant,Crowd Control Mace,Black,Male,20.0,Commission of Crime,1,Downtown West

In [57]:
df2["subject_injury"].describe()

count     3077
unique       2
top        Yes
freq      1631
Name: subject_injury, dtype: object

In [61]:
# Figuring out porpotion of Nans there are by dividing the sum of NaNs with the total number of rows

x = df2["subject_injury"].isna().sum()
y = len(df2)
x/y

np.float64(0.7619342359767892)

In [ ]:
#This means that 76% of the values indicating whether the subject was injured or not are missing. This is gravely concerning as that is 3/4s of the data for that column.

In [65]:
#Replacing the NaNs with "missing" to be able to cross tabulate and checking to ensure that it worked and that nothing was dropped
df2["subject_injury"] = df2["subject_injury"].fillna("Missing")
df2["subject_injury"].unique()
df2["subject_injury"].value_counts()

array(['Missing', 'No', 'Yes'], dtype=object)

In [66]:
#This crosstab helps us see that the missing 76% of data for subject_injury is not random and seems to be closely correlated with the type of force used. In force types where it seems pretty likely that the police would hurt a subject (aka bodily force/chemical irritant/taser/etc.), the data for whether the subject sustained injury is conspicously missing at alarming porportions.
pd.crosstab(df2["subject_injury"], df2["force_type"])

force_type,Baton,Bodily Force,Chemical Irritant,Firearm,Gun Point Display,Improvised Weapon,Less Lethal,Less Lethal Projectile,Maximal Restraint Technique,Police K9 Bite,Taser
subject_injury,,,,,,,,,,,
Missing,2,7051,1421,0,27,74,87,0,170,31,985
No,0,1093,131,2,33,34,0,1,0,2,150
Yes,2,1286,41,0,44,40,0,2,0,44,172

In [67]:
# question 2.1
from google.colab import files
uploaded = files.upload()

Saving GSAF5.xls to GSAF5.xls

## *Phase 2: AI-assisted Revision
Keep Phase 1 frozen.

- **Phase 1 commit SHA ID:** [To be provided]
- **AI tool and model used:** [To be provided]

### *Prompts used

1. [Paste prompt]
2. [Paste follow-up prompt]

### *AI-proposed changes

[Paste the AI's concise numbered list verbatim.]

1. ...
2. ...

### *Evaluation of AI suggestions

| Change | Decision | Reason and verification |
|---|---|---|
| 1 | Accept / modify / reject | ... |
| 2 | Accept / modify / reject | ... |

### *AI-assisted solution in full
After the evaluation of AI suggestions, incorporate the accepted revisions into your Phase 1 solution and provide the final Phase 2 solution in full in the following cells.

In [ ]:
# Your Phase 2 solution to the problem goes here.

### *Reflection on AI assistance
In your own words without generative AI.

[In 150–300 words, describe the main improvements, AI mistakes or limitations, how the final solution was verified, and any remaining concerns.]